# NumPy

*Chris Wu*  
*2016年12月*

---

这里主要介绍 Numpy 部分的内容。**Pandas 比 NumPy 在数据处理方面更强大**；如果你不想进行模型和算法方面的深入，而仅仅是处理数据，你可以跳过 NumPy 部分的内容。

我默认在全文的所有代码中加载下面这一行：

In [1]:
import numpy as np

# Numpy：数组计算

数组可以是高维的，但一般应用中是二维的（下文会将二维数组称为矩阵）。通常我们只会使用到二维的数组。

## 创建数组

数组的创建是最基础的。从列表用 np.array() 创建一个数组。

In [2]:
dt1 = [1, 2, 3, 4, 5, 6]
arr1 = np.array(dt1)
print(arr1)  # 一行六列的数组

[1 2 3 4 5 6]


In [3]:
dt2 = [[1, 2, 3], [4, 5, 6]]
arr2 = np.array(dt2)
print(arr2)  # 自动识别为两行三列

[[1 2 3]
 [4 5 6]]


数组的“尺寸”通过 shape 命令可以获知，维度通过 ndim 命令可以获知：

In [4]:
print(arr2.shape, '\n',  # 返回结果是一个元组(tuple)
      arr2.ndim, '\n',   # 返回结果是数组的维度（即“轴”的数量，这里只有行和列）
      arr2.size)         # 返回结果是数组的总元素个数

(2, 3) 
 2 
 6


## 特殊矩阵

有许多数学中经常使用的特殊矩阵，可以通过 NumPy 内置的函数简便地生成。

### 预分配内存：初始矩阵

预分配内存空间，但不赋任何值。当你需要一个很大的矩阵时，预先分配内存空间是需要考虑的。**注意：np.empty() 产生的矩阵并不是严格的全零矩阵！全零矩阵请使用后面介绍的命令 np.zeros().**

In [5]:
np.empty([2, 3])  # 不是严格全零的！

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

仿造一个现有的矩阵，创建一个尺寸相同的初始矩阵：

In [6]:
np.empty_like(arr2)  # 不是严格全零的！

array([[0, 0, 0],
       [0, 0, 0]])

### 全0矩阵 / 全1矩阵

命令 np.zeros([m, n]) 可以创建一个 m 行 n 列的矩阵。而 np.ones() 则可以创建全 1 矩阵。

In [7]:
np.ones([2, 3])  # 2行3列全零矩阵

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

同样，你也可以生成一个与现有矩阵尺寸一致的全零或全一矩阵：

In [8]:
np.ones_like(arr2)  # 与 np.ones(arr2.shape) 功能一样

array([[1, 1, 1],
       [1, 1, 1]])

In [9]:
np.zeros_like(arr2)

array([[0, 0, 0],
       [0, 0, 0]])

### 等差数列

命令 np.arange() 可以产生一系列等差数列值作为一个1行N列的矩阵。它非常像原生 Python 中的 range 命令。

In [10]:
np.arange(1, 9, 2)  # 不包括尾端数字“9”

array([1, 3, 5, 7])

但更通常地，我们使用 np.linspace 命令，因为这样**可以指定生成结果的元素个数**：

In [11]:
np.linspace(1, 7, 4)  # 包括尾端数字“7”，等距生成4个数

array([ 1.,  3.,  5.,  7.])

### 单位阵

单位阵，或称单位矩阵，仅主对角线是1，其余是0。

In [12]:
np.eye(2, 3)  # 可以是严格正方形单位阵，也可以不严格。

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.]])

In [13]:
np.identity(3)  # 严格正方形单位阵。

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

### 随机数矩阵

利用 np.random.rand（从0到1的均匀分布）或者 np.random.randn（标准正态分布）命令：

In [14]:
# 由于每次运行结果不一样，因此就不执行这两行了。
# np.random.rand(3, 2)
# np.random.randn(3, 2)

## 矩阵内操作

### 复制

NumPy 中对矩阵的任何截取操作**都不会产生新的变量**，除非你使用复制命令 copy()。如果你对原数据进行了更改，那么截取结果也会发生变化。例子：

In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
temp = arr[1]  # 第二行

arr[1] = [7, 8, 9]
temp

array([7, 8, 9])

In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
temp = arr[1].copy()  # 第二行

arr[1] = [7, 8, 9]
temp

array([4, 5, 6])

### 切片

与 Python 原生序列的切片操作类似：

In [17]:
arr[:, :2]

array([[1, 2],
       [7, 8]])

注意，如果只传入一个参数，默认是矩阵的行。比如这个表示矩阵的第二行：

In [18]:
arr[1]

array([7, 8, 9])

### 尺寸重塑

利用 arr.reshape(m, n) 命令可以把矩阵 arr 重塑成为一个 m 行 n 列的矩阵。**如果你想更改原矩阵而非产生一个新矩阵，使用 arr.resize 命令**。

In [19]:
arr = np.arange(0, 12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
arr.resize(2, 6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

另一个命令 arr.ravel() 则能把矩阵变为一个行向量。它还可以配合 order 参数。常用的取值有按照行读取（C，默认）或列读取（F）。

In [21]:
arr.ravel(order='F')

array([ 0,  6,  1,  7,  2,  8,  3,  9,  4, 10,  5, 11])

### 转置

矩阵的转置是常用的操作之一。

In [22]:
arr.T

array([[ 0,  6],
       [ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])

## 矩阵间操作

矩阵间的操作大致分为矩阵级和元素级两种。

### 矩阵乘法

矩阵的加减法没什么好说的。先看矩阵的乘法：

In [23]:
a = np.linspace(1, 6, 6).reshape(2, 3)
b = np.linspace(2, 7, 6).reshape(3, 2)
np.dot(a, b)  # 或者用 a.dot(b) 也可以改

array([[ 28.,  34.],
       [ 64.,  79.]])

### 矩阵组合

可以从竖直方向或者水平方向合并。

In [24]:
a = np.arange(1, 5).reshape(2, 2)
b = np.arange(5, 9).reshape(2, 2)

np.vstack((a, b))  # 也可以写 np.vstack([a, b])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [25]:
np.hstack((a, b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### 一元与二元函数

直接从元素操作中移植的函数，比如幂指函数等等。一元函数调用形式是 np.function(arr) 简表如下：

| 一元函数 | 含义 |
| --- | --- |
| abs/fabs | 求模。对于非复数矩阵，fabs更快。 |
| sqrt/square | 平方根/平方 |
| exp | 指数 |
| log/log10/log2/log1p | 对数：自然对数/10/2为底，以及以2为底的log(1+x) |
| sign | 正负号判断函数：返回 1, 0, 或者 -1 |
| ceil/floor | 向上取整/向下取整 |
| rint | 四舍五入到整数 |
| isnan | 返回关于非数值（np.nan）判断的布尔型数组 |
| isfinite/isinf | 判断非无限大值/无限大值 |
| sin/cos/tan | 三角函数 |
| arcsin/arccos/arctan | 反三角函数 |
| sinh/cosh/tanh/arcsinh/arccosh/arctanh | 以上三角函数的双曲形式 |

以及矩阵的二元函数，调用形式是 np.function(x, y)：

| 二元函数 | 含义 |
| --- | --- |
| add/substract/multiply | 对应元素相加/相减/相乘 |
| divide/floor_divide | 对应元素除法及向下整除法（弃余数） |
| power | 计算 x(i,j)^y(i,j) |
| maximum/fmax | 元素级的最大值。fmax 表示忽略 NaN |
| | *注：在比较含有 NaN 的矩阵时可能出现问题，我尚不清楚 NumPy 做出了怎样的改变。* |
| minimum/fmin | 仿上 |
| mod | 取余 |
| copysign | 将y的符号传递给x中的对应元素 |

### 统计函数

一些与统计相关的函数，或者简单分析矩阵数据特征的函数：

| 统计函数 | 含义 |
| --- | --- |
| average/mean | 平均值。其中 average 还可以用 weight 参数指定权重 |
| median | 中位数 |
| diff | 一阶差分 |
| cumsum/cumprod | 累和／累积 | 
| sum/prod | 求和 / 求积 |
| std/var | 标准差 / 方差 |

一些例子：

In [26]:
np.cumprod(np.arange(1, 7))  # 累积

array([  1,   2,   6,  24, 120, 720], dtype=int32)

In [27]:
np.average(np.arange(6).reshape((3,2)), axis=1, weights=[1./4, 3./4])  # 加权平均值

array([ 0.75,  2.75,  4.75])

In [28]:
np.abs(np.array([3 + 4j, -3]))  # 求模

array([ 5.,  3.])

In [29]:
arr2 = np.array([7, 6])
arr3 = np.array([1, np.inf])

np.fmax(arr2, arr3)   # 求最大值

array([  7.,  inf])

## 其他线性代数命令

In [30]:
arr = np.array([[1, 2], [4, 3]])

arr.T  # 矩阵转置。两者等效
arr.transpose()

array([[1, 4],
       [2, 3]])

In [31]:
np.linalg.inv(arr)  # 求逆矩阵

array([[-0.6,  0.4],
       [ 0.8, -0.2]])

In [32]:
np.trace(arr)  # 矩阵的迹（主对角线元素之和）

4

In [33]:
Y = np.array([5, 10]).reshape(2, 1)
np.linalg.solve(arr, Y)  # 解线性方程组 arr * X = Y

array([[ 1.],
       [ 2.]])

In [34]:
np.linalg.lstsq(arr, Y)  # 最小二乘解

(array([[ 1.],
        [ 2.]]),
 array([], dtype=float64),
 2,
 array([ 5.39834564,  0.92620968]))

In [35]:
np.linalg.qr(Y)  # QR分解

(array([[-0.4472136 ],
        [-0.89442719]]), array([[-11.18033989]]))

## 高级矩阵运算
### 条件逻辑：np.where

np.where(condition_arr, xarr, yarr) 表示：如果condition_arr 对应值为真，那么从 xarr 取值；否则从 yarr 取值。

In [36]:
xarr = np.array([[1, 2, 3],[-1, -2, 0], [4, 5, 6]])
np.where(xarr >= 0, xarr, np.nan)  # 把小于零的全部替换为 NaN

array([[  1.,   2.,   3.],
       [ nan,  nan,   0.],
       [  4.,   5.,   6.]])

### 布尔型矩阵：arr.any() / arr.all()

布尔型矩阵是指每个元素为 True 或者 False 的矩阵。

In [37]:
boolarr = np.array([False, True, False])
print(boolarr.any(),  # 是否存在 True
      boolarr.all())  # 是否全是 True

True False


### 唯一化和集合函数

所有重复的元素只保留一个，像集合一样。返回的结果是已排序过后的。

In [38]:
xarr = np.array([[1, 2, 2, 5], [3, -1, 4, 4]])
yarr = np.array([[-1, 2, 2, 6], [-2, -1, 1, 3]])
np.unique(xarr)

array([-1,  1,  2,  3,  4,  5])

In [39]:
print(np.intersect1d(xarr, yarr),  # 交集
      np.union1d(xarr, yarr),  # 并集
      np.in1d(xarr, yarr),  # xarr 中的对应元素是否在 yarr 中
      np.setdiff1d(xarr, yarr),  # 在 xarr 中但不在 yarr 中的元素
      np.setxor1d(xarr, yarr))  # 仅存在于 xarr / yarr 之一的元素

[-1  1  2  3] [-2 -1  1  2  3  4  5  6] [ True  True  True False  True  True False False] [4 5] [-2  4  5  6]


## 保存与读取

In [40]:
# 保存
# np.save(filename_string, arr)  # 把单个数组保存到 filename_string.npy 中
# np.savez(zipname_string, a=arr1, b=arr2, ...)  # 把多个数组压缩保存到 zipname_string.npz 中

# 读取
# arr = np.load('filename_string.npy')  # 直接获取单个数组
# arrzip = np.load('zipname_string.npz')  # 将压缩包读取到字典 arrzip 中
# arr1 = arrzip['a']

# 保存 / 读取 txt
# arr = np.loadtxt('txtname.txt', delimeter=',')  # 保存 txt 用savetxt

## 后记

NumPy 的基本就到这里结束了。对于数据处理而言，Pandas是更强大的工具。NumPy 和 SciPy 则可以共同完成很多数学计算方面的内容。