# Numpy & Pandas

*Chris Wu*  
*2016年10月*

---

这里主要介绍 Numpy 和 Pandas 部分的内容。默认在全文中使用：

In [1]:
import numpy as np
from pandas import Series, DataFrame

# Numpy：数组计算

## 创建数组

数组或者矩阵的创建是最基础的。从列表用 np.array() 创建一个数组。

In [2]:
dt1 = [1, 2, 3, 4, 5, 6]
arr1 = np.array(dt1)
print(arr1)  # 一行六列的数组

[1 2 3 4 5 6]


In [3]:
dt2 = [[1, 2, 3], [4, 5, 6]]
arr2 = np.array(dt2)
print(arr2)  # 自动识别为两行三列

[[1 2 3]
 [4 5 6]]


数组的“尺寸”通过 shape 命令可以获知：

In [4]:
arr2.shape  # 返回结果是一个元组(tuple)

(2, 3)