# NumPy

*Chris Wu*  
*2016年10月*

---

这里主要介绍 Numpy 部分的内容。默认在全文中使用：

In [1]:
import numpy as np

# Numpy：数组计算

数组可以是高维的，但一般应用中是二维的（下文会将二维数组称为矩阵）。通常我们只会使用到二维的数组。

## 创建数组

数组的创建是最基础的。从列表用 np.array() 创建一个数组。

In [2]:
dt1 = [1, 2, 3, 4, 5, 6]
arr1 = np.array(dt1)
print(arr1)  # 一行六列的数组

[1 2 3 4 5 6]


In [3]:
dt2 = [[1, 2, 3], [4, 5, 6]]
arr2 = np.array(dt2)
print(arr2)  # 自动识别为两行三列

[[1 2 3]
 [4 5 6]]


数组的“尺寸”通过 shape 命令可以获知：

In [4]:
arr2.shape  # 返回结果是一个元组(tuple)

(2, 3)

## 特殊矩阵

有许多数学中经常使用的特殊矩阵，可以通过 NumPy 内置的函数简便地生成。

### 预分配内存：初始矩阵

预分配内存空间，但不赋任何值。当你需要一个很大的矩阵时，预先分配内存空间是需要考虑的。**注意：np.empty() 产生的矩阵并不是严格的全零矩阵！全零矩阵请使用后面介绍的命令 np.zeros().**

In [5]:
np.empty([2, 3])  # 不是严格全零的！

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

仿造一个现有的矩阵，创建一个尺寸相同的初始矩阵：

In [6]:
np.empty_like(arr2)  # 不是严格全零的！

array([[0, 0, 0],
       [0, 0, 0]])

### 全0矩阵 / 全1矩阵

命令 np.zeros(m, n) 可以创建一个 m 行 n 列的矩阵。你也可以赋予它更多的维度（比如 np.zeros(m, n, p) 就能生成一个三维数组，但在这里不讨论）。而 np.ones() 则可以创建全一矩阵。

In [7]:
np.zeros(3)  # 1行3列全零矩阵

array([ 0.,  0.,  0.])

In [8]:
np.ones([2, 3])  # 2行3列全零矩阵

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

同样，你也可以生成一个与现有矩阵尺寸一致的全零或全一矩阵：

In [9]:
np.ones_like(arr2)  # 与 np.ones(arr2.shape) 功能一样

array([[1, 1, 1],
       [1, 1, 1]])

In [10]:
np.zeros_like(arr2)

array([[0, 0, 0],
       [0, 0, 0]])

### 等差数列

命令 np.arange() 可以产生一系列等差数列值作为一个1行N列的矩阵。它非常像原生 Python 中的 range 命令。

In [11]:
np.arange(1, 9, 2)  # 不包括尾端数字“9”

array([1, 3, 5, 7])

### 单位阵

单位阵，或称单位矩阵，仅主对角线是1，其余是0。

In [12]:
np.eye(2, 3)  # 可以是严格正方形单位阵，也可以不严格。

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.]])

In [13]:
np.identity(3)  # 严格正方形单位阵。

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

## 矩阵基本操作

### 复制

NumPy 中对矩阵的任何截取操作**都不会产生新的变量**，除非你使用复制命令 copy()。如果你对原数据进行了更改，那么截取结果也会发生变化。例子：

In [14]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
temp = arr[1]  # 第二行

arr[1] = [7, 8, 9]
temp

array([7, 8, 9])

In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
temp = arr[1].copy()  # 第二行

arr[1] = [7, 8, 9]
temp

array([4, 5, 6])

### 切片

与 Python 原生序列的切片操作类似：

In [16]:
arr[:, :2]

array([[1, 2],
       [7, 8]])

注意，如果只传入一个参数，默认是矩阵的行。比如这个表示矩阵的第二行：

In [17]:
arr[1]

array([7, 8, 9])

### 尺寸重塑

利用 arr.reshape(m, n) 命令可以把矩阵 arr 重塑成为一个 m 行 n 列的矩阵。

In [18]:
arr = np.arange(0, 12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### 转置

矩阵的转置是常用的操作之一。

In [19]:
arr.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

## 元素函数

直接从元素操作中移植的函数，比如幂指函数等等。一元函数调用形式是 np.function(arr) 简表如下：

| 一元函数 | 含义 |
| --- | --- |
| abs/fabs | 求模。对于非复数矩阵，fabs更快。 |
| sqrt/square | 平方根/平方 |
| exp | 指数 |
| log/log10/log2/log1p | 对数：自然对数/10/2为底，以及以2为底的log(1+x) |
| sign | 正负号判断函数：返回 1, 0, 或者 -1 |
| ceil/floor | 向上取整/向下取整 |
| rint | 四舍五入到整数 |
| isnan | 返回关于非数值（np.nan）判断的布尔型数组 |
| isfinite/isinf | 判断非无限大值/无限大值 |
| sin/cos/tan | 三角函数 |
| arcsin/arccos/arctan | 反三角函数 |
| sinh/cosh/tanh/arcsinh/arccosh/arctanh | 以上三角函数的双曲形式 |

以及矩阵的二元函数，调用形式是 np.function(x, y)：

| 二元函数 | 含义 |
| --- | --- |
| add/substract/multiply | 元素相加/相减/相乘 |
| divide/floor_divide | 除法及向下整除法（弃余数） |
| power | 计算 x(i,j)^y(i,j) |
| maximum/fmax | 元素级的最大值。fmax 表示忽略 NaN |
| | *注：在比较含有 NaN 的矩阵时可能出现问题，我尚不清楚 NumPy 做出了怎样的改变。* |
| minimum/fmin | 仿上 |
| mod | 取余 |
| copysign | 将y的符号传递给x中的对应元素 |

In [20]:
np.abs(np.array([3 + 4j, -3]))  # 求模

array([ 5.,  3.])

In [21]:
arr2 = np.array([7, 6])
arr3 = np.array([1, np.inf])

np.fmax(arr2, arr3)   # 求最大值

array([  7.,  inf])