# Numpy

*Chris Wu*  
*2016年10月*

---

这里主要介绍 Numpy 部分的内容。默认在全文中使用：

In [1]:
import numpy as np

# Numpy：数组计算

数组可以是高维的，但一般应用中是二维的（下文会将二维数组称为矩阵）。通常我们只会使用到二维的数组。

## 创建数组

数组的创建是最基础的。从列表用 np.array() 创建一个数组。

In [2]:
dt1 = [1, 2, 3, 4, 5, 6]
arr1 = np.array(dt1)
print(arr1)  # 一行六列的数组

[1 2 3 4 5 6]


In [3]:
dt2 = [[1, 2, 3], [4, 5, 6]]
arr2 = np.array(dt2)
print(arr2)  # 自动识别为两行三列

[[1 2 3]
 [4 5 6]]


数组的“尺寸”通过 shape 命令可以获知：

In [4]:
arr2.shape  # 返回结果是一个元组(tuple)

(2, 3)

## 特殊矩阵

有许多数学中经常使用的特殊矩阵，可以通过 NumPy 内置的函数简便地生成。

### 预分配内存：初始矩阵

预分配内存空间，但不赋任何值。当你需要一个很大的矩阵时，预先分配内存空间是需要考虑的。**注意：np.empty() 产生的矩阵并不是严格的全零矩阵！全零矩阵请使用后面介绍的命令 np.zeros().**

In [5]:
np.empty([2, 3])  # 不是严格全零的！

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

仿造一个现有的矩阵，创建一个尺寸相同的初始矩阵：

In [6]:
np.empty_like(arr2)  # 不是严格全零的！

array([[0, 0, 0],
       [0, 0, 0]])

### 全0矩阵 / 全1矩阵

命令 np.zeros(m, n) 可以创建一个 m 行 n 列的矩阵。你也可以赋予它更多的维度（比如 np.zeros(m, n, p) 就能生成一个三维数组，但在这里不讨论）。而 np.ones() 则可以创建全一矩阵。

In [7]:
np.zeros(3)  # 1行3列全零矩阵

array([ 0.,  0.,  0.])

In [8]:
np.ones([2, 3])  # 2行3列全零矩阵

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

同样，你也可以生成一个与现有矩阵尺寸一致的全零或全一矩阵：

In [9]:
np.ones_like(arr2)  # 与 np.ones(arr2.shape) 功能一样

array([[1, 1, 1],
       [1, 1, 1]])

In [10]:
np.zeros_like(arr2)

array([[0, 0, 0],
       [0, 0, 0]])

### 等差数列

命令 np.arange() 可以产生一系列等差数列值作为一个1行N列的矩阵。它非常像原生 Python 中的 range 命令。

In [11]:
np.arange(1, 9, 2)  # 不包括尾端数字“9”

array([1, 3, 5, 7])

### 单位阵

单位阵，或称单位矩阵，仅主对角线是1，其余是0。

In [12]:
np.eye(2, 3)  # 可以是严格正方形单位阵，也可以不严格。

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.]])

In [13]:
np.identity(3)  # 严格正方形单位阵。

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

## 矩阵基本操作

### 复制

NumPy 中对矩阵的任何截取操作**都不会产生新的变量**，除非你使用复制命令 copy()。如果你对原数据进行了更改，那么截取结果也会发生变化。例子：

In [14]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
temp = arr[1]  # 第二行

arr[1] = [7, 8, 9]
temp

array([7, 8, 9])

In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
temp = arr[1].copy()  # 第二行

arr[1] = [7, 8, 9]
temp

array([4, 5, 6])